project:
  type: website
  output-dir: docs

website:
  title: "RSE Argentina"
  description: "Research Software Engineering en Argentina"
  favicon: image/rse_arg.png 
  
  navbar:
    logo: image/rse_arg.png 
    background: primary
    right:
      - text: "Inicio"
        href: index.qmd
      - text: "¿Qué es RSE?"
        href: que-es-rse.qmd
      - text: "Quiénes Somos"
        href: quienes-somos.qmd
      - text: "Código de Conducta"
        href: coc.qmd       
      - text: "Actividades"
        href: actividades.qmd
      - text: "Recursos"
        href: recursos.qmd
      - text: "Contacto"
        href: contacto.qmd
    left:
      - icon: github
        href: https://github.com/rse-argentina

  page-footer:
    center: |
      © 2025 RSE Argentina - Equipo organizador. Todos los derechos reservados.
    background: light

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    lang: es

execute:
  freeze: true
