---
title: "Código de Conducta"
---

Quienes organizamos RSE Argentina nos comprometemos a fomentar un ambiente abierto, seguro y amigable, y garantizar la participación de todas las personas en nuestra comunidad  (lo que incluye actividades tanto virtuales como presenciales: talleres, conversatorios, entre otros) independientemente de su edad, género, orientación sexual, discapacidad, apariencia física, nacionalidad, raza, etnia, religión (o la falta de ella), ideología u opciones tecnológicas.

Todas las personas que participen en este espacio, incluyendo coordinadores, colaboradores y asistentes, deberán aceptar y respetar el siguiente código de conducta.

### Alcance

Este código de conducta se aplica a todos los espacios de la comunidad de RSE Argentina, incluyendo encuentros virtuales y presenciales, la cuenta de correo electrónico, redes sociales, la organización en GitHub y sus repositorios, así como cualquier otro medio vinculado a la comunidad o en el que RSE Argentina participe.

### Ejemplos de comportamientos que contribuyen a crear un ambiente positivo en nuestra comunidad.

-   Demostrar empatía y amabilidad ante otras personas
-   Respetar diferentes opiniones, puntos de vista y experiencias
-   Dar y aceptar adecuadamente retroalimentación constructiva
- Centrarse en lo que sea mejor no sólo para nosotros como personas, sino para la comunidad en general
-   Aceptar la responsabilidad y disculparse ante quienes afectamos por nuestros errores, involuntarios o no, aprendiendo de la experiencia
-    Realizar contribuciones relevantes brindando el crédito necesario y requerido según las disposiciones regionales.

### Ejemplos de comportamiento inaceptable.

-   El uso de lenguaje o imágenes sexualizadas como también atención o avances sexuales no deseados
-   Comentarios despectivos, insultantes y/o ataques personales
-   Cualquier tipo de acoso en público o privado
-  Publicar información privada de otras personas, tales como direcciones físicas o de correo electrónico, sin permiso explícito
-   El plagio o la violación de derechos de autor o propiedad de cualquier tipo
- Cualquier tipo de maltrato, destrato; incluyendo ignorar, avergonzar,
invisibilizar, denigrar, censurar, etc.
-   Otras conductas que puedan ser razonablemente consideradas como inapropiadas en un entorno profesional.



### Responsabilidades del equipo coordinador

[Quienes coordinan RSE Argentina](https://rse-argentina.github.io/quienes-somos.html#coordinaci%C3%B3n) son responsables de aclarar los estándares de comportamiento aceptable y se reservan el derecho de admisión o permanencia, temporal o permanente, en la comunidad para cualquier caso de comportamiento considerado inaceptable.

También tienen la responsabilidad y se reservan el derecho de eliminar, editar o rechazar comentarios, materiales y otras contribuciones que no estén alineadas con este Código de Conducta.


### ¿Necesitás ayuda o querés reportar una situación?

Los casos de comportamiento inaceptable pueden ser informados enviando un correo electrónico a **rse.comunidad.argentina\@gmail.com** con "ASUNTO: Código de conducta".

Todos los reportes serán revisados y recibirán una respuesta acorde a las circunstancias. En todo momento se garantizará la confidencialidad y la seguridad de las personas afectadas y/o de quienes realicen el reporte.

::: callout-important
**Si presenciás una situación que vulnere este código de conducta, te invitamos a reportarla por este medio.**
:::



> *Adaptado de las [Pautas de convivencia de MetaDocencia](https://zenodo.org/records/12534196) y del [código de conducta de LatinR](https://latinr.org/sobre/coc/):*.

