---
title: "Quiénes Somos"

---

## Coordinación

RSE Argentina es una iniciativa comunitaria coordinada por un equipo de voluntarias comprometidas con visibilizar y fortalecer el rol de las personas encargadas de desarrollar software de investigación.


:::: {.columns}

::: {.column width="45%"}

::: hex-card
#### Patricia A.Loto

**Coordinadora**

Licenciada en sistemas de Información recibida en la UNNE, actualmente cursando un máster en Tecnologías de la Información, con varios años de experiencia en distintos roles técnicos, helpdesk, analista funcional, diseño de base de datos y desarrolladora de software. Apasionada por el código reproducible y la ciencia abierta.

  📧 patricia.andrea.loto\@gmail.com | [**GitHub**](https://github.com/patriloto) | [**LinkedIn**](https://www.linkedin.com/in/patricia-loto/) 
:::

:::

::: {.column width="10%"}

:::

::: {.column width="45%"}

::: hex-card
#### Andrea Gomez Vargas

**Coordinadora**

Socióloga & Analista de Estadísticas de Población. Especialista en el procesamiento de grandes volúmenes de datos. Mi enfoque combina las Ciencias Sociales con el desarrollo de software científico, aplicando metodologías de reproducibilidad para garantizar el rigor técnico en la investigación social abierta.

  📧 andrea\@rladies.org | [**GitHub**](https://github.com/SoyAndrea) | [**LinkedIn**](https://www.linkedin.com/in/andreasociologa/)
:::

:::

::::

:::: {.columns}

::: {.column width="27%"}

:::

::: {.column width="46%"}

::: hex-card

#### Jesica Formoso

**Colaboradora**

Doctora en Ciencias Éticas, Humanísticas y Sociales Médicas (UBA) e Investigadora en psicología cognitiva en CONICET. Especialista en estadística aplicada a las ciencias de la salud (UBA). Promuevo activamente la ciencia abierta y el desarrollo de herramientas abiertas a través de mi participación en equipos de investigación y en comunidades de práctica.


📧 jformoso\@conicet.gov.ar | [**GitHub**](https://github.com/JesiFormoso) | [**LinkedIn**](https://www.linkedin.com/in/jesica-formoso-16ab4649/)

:::

::: {.column width="27%"}

:::

:::

::::


## Gobernanza

RSE Argentina funciona como una comunidad horizontal con decisiones tomadas por consenso. Nuestros principios son:

-   **Inclusión**: Todas las personas interesadas en la temática son bienvenidas sin importar su nivel o experiencia
-   **Colaboración**: Compartimos conocimientos abiertamente
-   **Diversidad**: Valoramos diferentes perspectivas y experiencias


## Historia


La idea de formar la comunidad de RSE en Argentina surgió durante la conferencia de Software de Investigación [RSECon25](https://rsecon25.society-rse.org/), realizada en Warwick en septiembre de 2025. Gracias a una beca para asistir, pudimos conocer de cerca la experiencia de la comunidad RSE a nivel internacional. Inspiradas por iniciativas similares en otros países, y considerando que en nuestra región solo existe actualmente un grupo, decidimos crear un espacio para:

-   Compartir experiencias y desafíos comunes
-   Promover el reconocimiento del trabajo del sesarrollador de software científico
-   Establecer conexiones con la red internacional de RSE


### Hitos importantes

#### **Septiembre 2025**

Ideas y sinergia para crear el grupo en Argentina después de participar en la RSECon25

#### **Octubre 2025**

**#IntlRSEday: celebramos el día internacional del software de investigación** - Charla inicial organizada entre RSE Chile, R en Buenos Aires, R-Ladies Resistencia-Corrientes y R-Ladies de Chile, comunidades amigas que se unieron para dar a conocer sobre RSE en nuestra región y en nuestro idioma.

Este fue un primer encuentro abierto regional, un antecedente clave para lo que luego daría origen a la comunidad de RSE en Argentina. 

<iframe src="https://www.youtube.com/embed/EYbg-Z0pgUs" width="100%" height="400" frameborder="0" allowfullscreen></iframe>

#### **Enero 2026**

Lanzamiento oficial de la comunidad de práctica y del sitio web


#### **Abril - Julio 2026**

Serie de Charlas sobre Software de Investigación


## Red de comunidades amigas:

-   [**RSE en Chile**](https://rse-chile.github.io/)

-   [**R-Ladies Resistencia-Corrientes**](https://github.com/RLadiesResistenciaCorrientes)

-   [**R en Buenos Aires**](https://github.com/renbaires)



> Agradecemos a RSECon25 por la beca otorgada, que no solo permitió ampliar la diversidad de participantes, sino también dar origen a RSE Argentina, y a RSE Chile por su rol pionero en la región.


