---
title: "Recursos"
---

## Guías y tutoriales

### Para empezar

-   📚 [**A not-so-brief history of Research Software Engineers**](https://www.software.ac.uk/blog/not-so-brief-history-research-software-engineers-0) - Una historia no tan breve de la ingeniería de software de investigación por el Software Sustainability Institute
-   🎓 [**Good Enough Practices in Scientific Computing**](https://carpentries.org/) - Lección sobre buenas prácticas para computación científica por The Carpentries
-   📖 [**Good enough practices in scientific computing**](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510) - Paper fundamental sobre buenas prácticas en computación científica

### Desarrollo de software científico

-   🐍 [**Scientific Python Tutorials**](https://learn.scientific-python.org/) - Tutoriales de Python Científico
-   📊 [**R for Data Science**](https://r4ds.had.co.nz/) - Libro sobre R para Ciencia de datos
-   🔧 [**Research Software Engineering with Python**](https://alan-turing-institute.github.io/rse-course/html/index.html) - Curso completo de Ingeniería de Software de investigación con python por el Alan Turing Institute
-   📦 [**Reproducible Research in R**](https://ropensci.org/packages/) - Investigación rerpoducible en R por rOpenSci
-   📖 [**Intro a la programación**](https://intro-programacion.netlify.app) - Curso introductorio de programación totalmente en español 
-   📖 [**Material de entrenamiento del programa de campeones de rOpenSci**](https://champions-program.ropensci.org/resources/resources.html) - Incluye diferentes tópicos como Git, desarrollo de paquetes, revisión de software, entre otros.


## Contribuir recursos

¿Conoces algún recurso valioso que no está en la lista? ¡Ayúdanos a mejorar esta sección abriendo un issue y sumando tu sugerencia!





